// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/NpoolPlatform/order-manager/pkg/db/ent/schema"
	"github.com/NpoolPlatform/order-manager/pkg/db/ent/state"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	stateMixin := schema.State{}.Mixin()
	state.Policy = privacy.NewPolicies(stateMixin[0], schema.State{})
	state.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := state.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	stateMixinFields0 := stateMixin[0].Fields()
	_ = stateMixinFields0
	stateFields := schema.State{}.Fields()
	_ = stateFields
	// stateDescCreatedAt is the schema descriptor for created_at field.
	stateDescCreatedAt := stateMixinFields0[0].Descriptor()
	// state.DefaultCreatedAt holds the default value on creation for the created_at field.
	state.DefaultCreatedAt = stateDescCreatedAt.Default.(func() uint32)
	// stateDescUpdatedAt is the schema descriptor for updated_at field.
	stateDescUpdatedAt := stateMixinFields0[1].Descriptor()
	// state.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	state.DefaultUpdatedAt = stateDescUpdatedAt.Default.(func() uint32)
	// state.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	state.UpdateDefaultUpdatedAt = stateDescUpdatedAt.UpdateDefault.(func() uint32)
	// stateDescDeletedAt is the schema descriptor for deleted_at field.
	stateDescDeletedAt := stateMixinFields0[2].Descriptor()
	// state.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	state.DefaultDeletedAt = stateDescDeletedAt.Default.(func() uint32)
	// stateDescOrderID is the schema descriptor for order_id field.
	stateDescOrderID := stateFields[1].Descriptor()
	// state.DefaultOrderID holds the default value on creation for the order_id field.
	state.DefaultOrderID = stateDescOrderID.Default.(func() uuid.UUID)
	// stateDescState is the schema descriptor for state field.
	stateDescState := stateFields[2].Descriptor()
	// state.DefaultState holds the default value on creation for the state field.
	state.DefaultState = stateDescState.Default.(string)
	// stateDescID is the schema descriptor for id field.
	stateDescID := stateFields[0].Descriptor()
	// state.DefaultID holds the default value on creation for the id field.
	state.DefaultID = stateDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.10.1"                                         // Version of ent codegen.
	Sum     = "h1:dM5h4Zk6yHGIgw4dCqVzGw3nWgpGYJiV4/kyHEF6PFo=" // Sum of ent codegen.
)
